// Code generated by Axiom CLI; DO NOT EDIT.

// Package axiom provides the Context interface and all platform capabilities
// injected into every node function.
//
// All capabilities are accessed through the single ax parameter:
//
//	ax.Log().Info("order processed", "order_id", "abc123", "total", 99.99)
//	apiKey, ok := ax.Secrets().Get("ANTHROPIC_API_KEY")
//
// Adding new platform capabilities requires no change to node function
// signatures — they are accessed via the Context interface.
package axiom

// Logger is a structured logger pre-configured for a single node invocation.
// Concurrent invocations each receive their own Logger instance — never share
// a Logger across calls. The platform injects it via Context; node authors
// never construct one directly.
type Logger interface {
	Debug(msg string, args ...any)
	Info(msg string, args ...any)
	Warn(msg string, args ...any)
	Error(msg string, args ...any)
}

// Secrets provides read-only access to the tenant secrets resolved by the
// platform at invocation time. Values are plaintext strings; the platform
// handles encryption and decryption. Node authors never construct a Secrets
// instance directly — the platform injects it via Context on every invocation.
type Secrets interface {
	// Get returns the value for the named secret and true when present.
	// Returns ("", false) when the secret was not resolved for this invocation.
	Get(name string) (string, bool)
}

// Memory provides access to the agent memory layer (ADR-002, pending implementation).
// This stub will be expanded with Search, Store, and Forget methods once the
// memory layer is implemented. Do not rely on its shape until ADR-002 is
// accepted and implemented.
type Memory interface{}

// Context is the single platform capability injection point for every node
// handler function. It is passed as the second parameter (ax) to every handler:
//
//	func MyNode(ctx context.Context, ax axiom.Context, input *gen.MyRequest) (*gen.MyResponse, error) {
//	    ax.Log().Info("handling", "id", input.GetId())
//	    key, ok := ax.Secrets().Get("MY_SECRET")
//	    ...
//	}
//
// Adding new platform capabilities requires no change to existing node
// function signatures — all capabilities are accessed via methods on Context.
type Context interface {
	// Log returns the structured logger for this invocation. Use instead of fmt.Println.
	Log() Logger

	// Secrets returns the tenant secrets resolver for this invocation.
	Secrets() Secrets

	// Memory returns the agent memory layer (ADR-002 stub — not yet implemented).
	Memory() Memory

	// ExecutionID returns the UUID of the current execution.
	ExecutionID() string

	// FlowID returns the stable ID of the graph artifact (constant across executions).
	FlowID() string

	// TenantID returns the UUID of the tenant that owns this invocation.
	TenantID() string
}
