// Code generated by Axiom CLI; DO NOT EDIT.

// Package axiom provides the Logger interface injected into every node function.
//
// In local development (axiom dev) the logger writes concise plain text to the
// terminal. In production it writes JSON with trace_id, span_id, and
// execution_id baked in, making every log line searchable by execution and
// linkable to its distributed trace in Grafana.
//
// Use it instead of fmt.Println for anything you want visible in production:
//
//	log.Info("order processed", "order_id", "abc123", "total", 99.99)
package axiom

// Logger is a structured logger pre-configured for a single node invocation.
// Concurrent invocations each receive their own Logger instance — never share
// a Logger across calls. The platform injects it; node authors never construct
// one directly.
type Logger interface {
	Debug(msg string, args ...any)
	Info(msg string, args ...any)
	Warn(msg string, args ...any)
	Error(msg string, args ...any)
}
