// Code generated by Axiom CLI; DO NOT EDIT.

// Package axiom provides the Logger and Secrets interfaces injected into every
// node function.
//
// In local development (axiom dev) the logger writes concise plain text to the
// terminal. In production it writes JSON with trace_id, span_id, and
// execution_id baked in, making every log line searchable by execution and
// linkable to its distributed trace in Grafana.
//
// Use it instead of fmt.Println for anything you want visible in production:
//
//	log.Info("order processed", "order_id", "abc123", "total", 99.99)
//
// Secrets are resolved by the platform at invocation time. Use them to access
// API keys and connection strings without embedding credentials in node code:
//
//	apiKey, ok := secrets.Get("ANTHROPIC_API_KEY")
package axiom

// Logger is a structured logger pre-configured for a single node invocation.
// Concurrent invocations each receive their own Logger instance — never share
// a Logger across calls. The platform injects it; node authors never construct
// one directly.
type Logger interface {
	Debug(msg string, args ...any)
	Info(msg string, args ...any)
	Warn(msg string, args ...any)
	Error(msg string, args ...any)
}

// Secrets provides read-only access to the tenant secrets resolved by the
// platform at invocation time. Values are plaintext strings; the platform
// handles encryption and decryption. Node authors never construct a Secrets
// instance directly — the platform injects it on every invocation.
type Secrets interface {
	// Get returns the value for the named secret and true when present.
	// Returns ("", false) when the secret was not resolved for this invocation.
	Get(name string) (string, bool)
}
